# Version of the Icarus theme that is currently used
version: 6.1.0

# Appearance
appearance:
    # Theme color scheme
    # Choose from "default", "cyberpunk", "dark", "light"
    theme: default
    # Code highlight theme
    # Choose from "atom-one-dark", "atom-one-light", "default", "github", "github-gist", "monokai", "rainbow", "vs", "vs2015", "xcode"
    highlight: atom-one-dark
    # Article thumbnail
    thumbnail: true
    # Favicon
    favicon: /img/favicon.svg
    # Fold categories
    fold_categories: true
    # Navigation bar logo
    logo: /img/logo.svg

# Profile specifies author information, social links, and links to services like donation and e-mail feedback.
profile:
    # Your name
    name: Owl Master
    # A brief bio about you
    bio: '艺术家、创作者、梦想家。在这里分享我的创作世界。'
    # Your avatar
    avatar: /img/avatar.png
    # Links to your social accounts
    social_links:
        # Get the icon name from https://fontawesome.com/icons
        Github:
            icon: fab fa-github
            url: https://github.com/owlmaster
        Twitter:
            icon: fab fa-twitter
            url: https://twitter.com/owlmaster
        Instagram:
            icon: fab fa-instagram
            url: https://instagram.com/owlmaster

# CDN provider for third-party libraries
cdn: jsdelivr

# A list of file paths to your custom CSS and JS files
assets:
    - _data/style.styl

# A list of your website's navigation links
navbar:
    menu:
        主页: /
        作品集: /portfolio/
        归档: /archives/
        关于: /about/

# The footer of your website
footer:
    # Links to your social accounts
    social_links:
        Github:
            icon: fab fa-github
            url: https://github.com/owlmaster
        Twitter:
            icon: fab fa-twitter
            url: https://twitter.com/owlmaster
        RSS:
            icon: fas fa-rss
            path: /atom.xml

# Post-related configurations
post:
    # The thumbnail of a post
    thumbnail: true
    # The banner of a post
    banner: true
    # Read more link
    read_more: true

# Page-related configurations
page:
    # The thumbnail of a page
    thumbnail: true
    # The banner of a page
    banner: true

# Sidebar configurations
sidebar:
    # Left sidebar configurations
    left:
        # Whether the sidebar sticks to the top when page scrolls
        sticky: true
    # Right sidebar configurations
    right:
        # Whether the sidebar sticks to the top when page scrolls
        sticky: true

# Widgets to be shown in the sidebar
widgets:
    # Recent posts widget
    - type: recent_posts
      # Where should the widget be placed, left or right
      position: left
    # Archives widget
    - type: archives
      # Where should the widget be placed, left or right
      position: left
    # Categories widget
    - type: categories
      # Where should the widget be placed, left or right
      position: left
    # Tags widget
    - type: tags
      # Where should the widget be placed, left or right
      position: left
    # Table of contents widget
    - type: toc
      # Where should the widget be placed, left or right
      position: right

# Search plugin configurations
search:
    # Name of the search plugin
    # Choose from "algolia", "baidu", "google", "hexo", "insight", "swiftype"
    type: insight

# Comment plugin configurations
comment:
    # Name of the comment plugin
    type: disqus
    # Disqus shortname
    shortname: owlempire

# Donation plugin configurations
donation:
    # Name of the donation plugin
    type: paypal
    # Paypal business ID or email
    business: your-paypal-email@example.com
    # Currency code
    currency_code: USD

# Share plugin configurations
share:
    # Name of the share plugin
    type: sharethis
    # Share plugin install code
    install_url: //platform-api.sharethis.com/js/sharethis.js#property=your-sharethis-property-id&product=inline-share-buttons

# Plugin configurations
plugins:
    # Enable page animation
    animejs: true
    # Enable back to top button
    back_to_top: true
    # Enable image gallery
    gallery: true
    # Enable search
    search: true
    # Enable page loading progress bar
    progressbar: true 